// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'printer.freezed.dart';

Future<String> printReceipt({
  required PrinterConnection connection,
  required String templateJson,
  required String dataJson,
}) => RustLib.instance.api.crateApiPrinterPrintReceipt(
  connection: connection,
  templateJson: templateJson,
  dataJson: dataJson,
);

Future<String> renderReceipt({
  required String templateJson,
  required String dataJson,
}) => RustLib.instance.api.crateApiPrinterRenderReceipt(
  templateJson: templateJson,
  dataJson: dataJson,
);

Future<String> openCashDrawer({
  required PrinterConnection connection,
  required int pin,
  required int onMs,
  required int offMs,
}) => RustLib.instance.api.crateApiPrinterOpenCashDrawer(
  connection: connection,
  pin: pin,
  onMs: onMs,
  offMs: offMs,
);

Future<String> listUsbPrinters() =>
    RustLib.instance.api.crateApiPrinterListUsbPrinters();

Future<String> discoverNetworkPrinters({
  required int timeoutMs,
  required List<String> serviceTypes,
}) => RustLib.instance.api.crateApiPrinterDiscoverNetworkPrinters(
  timeoutMs: timeoutMs,
  serviceTypes: serviceTypes,
);

@freezed
sealed class PrinterConnection with _$PrinterConnection {
  const PrinterConnection._();

  /// 网络打印机（TCP/IP 直连）。
  /// host: IP 或主机名
  /// port: 端口号，常见 9100
  /// timeout_ms: 连接超时毫秒数
  const factory PrinterConnection.network({
    required String host,
    required int port,
    required int timeoutMs,
  }) = PrinterConnection_Network;

  /// USB 打印机。
  /// vendor_id: USB 厂商 ID（十六进制，如 0x0525）
  /// product_id: USB 产品 ID（十六进制，如 0xa700）
  const factory PrinterConnection.usb({
    required int vendorId,
    required int productId,
  }) = PrinterConnection_Usb;

  /// 串口打印机。
  /// port: 串口路径（如 /dev/ttyUSB0、COM3）
  /// baud_rate: 波特率（常见 9600、115200）
  const factory PrinterConnection.serial({
    required String port,
    required int baudRate,
  }) = PrinterConnection_Serial;
}
